name: quickcam
description: "A camera app with Supabase storage"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  image_picker: ^1.0.4
  supabase_flutter: ^2.10.3
  path_provider: ^2.1.1
  path: ^1.8.3
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  permission_handler: ^11.0.1
  url_launcher: ^6.1.7 
  cupertino_icons: ^1.0.8

dependency_overrides:
  supabase: ^2.10.0
  gotrue: ^2.16.0
  storage_client: ^2.4.1
  postgrest: ^2.5.0
  realtime_client: ^2.6.0
  functions_client: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true